name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, repopened, edited]

permissions:
  contents: read  # Grants read access to the repository content.
  pull-requests: write # Grants write access to pull requests (needed to add labels).

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull Request Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configurationPath: .github/labeler.yml
